### ISSUE TITLE
Add libgtsam.so symlink in gtsam install script

### ISSUE THREAD

**Issue by qinjunj** [ILLIXR/ILLIXR#313]
Running ILLIXR raises error because of missing libgtsam.so in /usr/local/lib. Fixed by symlink libgtsamRelWithDebInfo.so to libgtsam.so.

**Comment by qinjunj** [comment]
Yes, absolute path needed. 
sudo ln -s /usr/local/lib/${so_file} /usr/local/lib/${so_file_release}

**Comment by charmoniumQ** [comment]
Maybe it would also be good to make add a failing example to our CI (test-driven development).

**Comment by mhuzai** [comment]
I know this was resolved in #314, but I'm not sure if `install_gtsam.sh` is as clean as it could be right now.
1. My first question is why doesn't the code on line 83 work. The correct symlink is updated _before_ `make install`, and so shouldn't the installed symlink in `/usr/local/lib` be the correct one?
2. Lines 86-90 are bogus anyway because the "unstable" symlink is actually in `${build_dir}/gtsam_unstable` and not in `${build_dir}/gtsam`.

If the answer to (1) above is that local symlinks get removed during `make install`, then we should remove lines 73-94. But if local symlinks do get preserved, then the cleaner solution would be to fix whatever is wrong with line 83 and then remove line 96.

**Comment by charmoniumQ** [comment]
I concur. This issue should remain open until we answer these questions, take their implied action, and catch this class of errors in CI. But who should we assign it to?
