### ISSUE TITLE
Required GPU specifications

### ISSUE THREAD

**Issue by vidishar11** [ILLIXR/ILLIXR#398]
what is the min GPU requirements to run ILLIXR ? I checked the documentation but could not found any. Also what is the max GPU requirements to test out max load ? Thanks!

**Comment by shg8** [comment]
Thanks for raising the issue. Minimally, we require Vulkan 1.2 or OpenGL 3.3. For a minimum load application, check out the plugins `vkdemo` and `gldemo` for the Vulkan and OpenGL pipeline respectively. Otherwise, if you're running an OpenXR application, it would be application dependent. If you'd like to test out a max load, Unreal 5 has some pretty heavy demo scenes.

**Comment by vidishar11** [comment]
Thank You shg8, but it would be really helpful if you could you please share the exact GPU make and its specifications which was used to run and test ILLIXR  in min load and max load. Likewise can u share the same for processor/CPU, RAM, Camera, IMU, Eye Tracking, Audio ?    Thanks!

**Comment by Jebbly** [comment]
You can refer to [the ILLIXR paper](http://rsim.cs.illinois.edu/Pubs/IISWC_2021_ILLIXR.pdf), which goes into spec details in Section 3.A. Some details are provided on which PC specs, cameras, and software libraries were used for the experimental setups. The paper also mentions the applications that were tested in Section 3.C. 

As @shg8 mentioned, you can also run arbitrarily complex OpenXR apps (e.g. packaged from Unreal Engine 5) if you'd like to test heavier apps than the ones mentioned in the original paper.

**Comment by Jebbly** [comment]
Closing this issue for the time being - feel free to ask follow-up questions on our Discord!
