### ISSUE TITLE
Explore OpenXR and OpenGL extensions for depth, vsync, and preemption priority

### ISSUE THREAD

**Issue by charmoniumQ** [ILLIXR/ILLIXR#47]

**Comment by mhuzai** [comment]
[XR_KHR_composition_layer_depth](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_composition_layer_depth) allows the application to submit depth buffers along with rendered images. It has already been implemented in Monado, and we can use it once we upgrade to latest Monado.

[XR_KHR_android_thread_settings](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_KHR_android_thread_settings) allows the application to tell the runtime which of its threads are higher priority and which are normal/low priority, so that the runtime can schedule them accordingly. Unfortunately, it is only available on Android.

There is currently no extension for vsync. However, there is [one](https://github.com/KhronosGroup/Vulkan-Docs/pull/1364) in the works.

Given the above, no extra work is required on our behalf at the moment.
